### ISSUE TITLE
ParserDailyVolumeTooLow

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#308] opened 2018-06-01 01:52 UTC
Alertmanager URL: https://mlab:YOztKFSKnRMz2GN1qFPueAku9WhmDYV2@alertmanager.mlab-oti.measurementlab.net

  * firing https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=sum%28increase%28etl_test_count%7Bservice%21~%22.%2Abatch.%2A%22%2Cstatus%3D%22ok%22%7D%5B1d%5D%29%29&#43;BY&#43;%28service%29&#43;%3C&#43;%280.7&#43;%2A&#43;quantile%280.5%2C&#43;label_replace%28sum%28increase%28etl_test_count%7Bservice%21~%22.%2Abatch.%2A%22%2Cstatus%3D%22ok%22%7D%5B1d%5D&#43;OFFSET&#43;1d%29%29&#43;BY&#43;%28service%29%2C&#43;%22delay%22%2C&#43;%221d%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28sum%28increase%28etl_test_count%7Bservice%21~%22.%2Abatch.%2A%22%2Cstatus%3D%22ok%22%7D%5B1d%5D&#43;OFFSET&#43;3d%29%29&#43;BY&#43;%28service%29%2C&#43;%22delay%22%2C&#43;%223d%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28sum%28increase%28etl_test_count%7Bservice%21~%22.%2Abatch.%2A%22%2Cstatus%3D%22ok%22%7D%5B1d%5D&#43;OFFSET&#43;5d%29%29&#43;BY&#43;%28service%29%2C&#43;%22delay%22%2C&#43;%225d%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28sum%28increase%28etl_test_count%7Bservice%21~%22.%2Abatch.%2A%22%2Cstatus%3D%22ok%22%7D%5B1d%5D&#43;OFFSET&#43;1w%29%29&#43;BY&#43;%28service%29%2C&#43;%22delay%22%2C&#43;%227d%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c1%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-disco-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c2%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-disco-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c1%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-ndt-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c2%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-ndt-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c1%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-sidestream-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c2%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-sidestream-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c1%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-traceroute-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29&#43;or&#43;label_replace%28label_replace%28vector%280%29%2C&#43;%22delay%22%2C&#43;%22c2%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%2C&#43;%22service%22%2C&#43;%22etl-traceroute-parser%22%2C&#43;%22%22%2C&#43;%22.%2A%22%29%29&#43;BY&#43;%28service%29%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = ParserDailyVolumeTooLow
    - service = etl-ndt-parser
    - severity = page
  
    Annotations:
  
    - hints = Are machines online? Is data being collected? Is the parser working?
    - summary = Today&#39;s test volume is less than 70% of nominal daily volume.
    - url = http://status.mlab-oti.measurementlab.net:3000/dashboard/file/Alert_ParserDailyVolumeTooLow.json

TODO: add graph url from annotations.

**Comment by pboothe** [comment] 2018-06-01 16:36
The switch at dfw03 was broken for a week. When it came back, things on the nodes were messed up. I have requested that OTI ops reboot the nodes.

**Comment by pboothe** [comment] 2018-06-01 16:42
This alert was caused by a push of bad cloud function code. Things have been fixed with https://github.com/m-lab/etl/pull/506 and https://github.com/m-lab/etl/pull/507

The alert will keep firing for the next ~24 hours, though. I have silenced this alert for the next 24 hours.

**Comment by pboothe** [comment] 2018-06-01 16:43
If it fires again, then we will want to be notified about it, because it will mean that I failed to fix it. Closing this issue.

**Closed by pboothe** 2018-06-01 16:43 UTC
Labels: Sprint 10, p0
